import "./globals.css";
import Nav from "@/app/ui/nav";
import MenuModal from "./ui/menuModal";
import { manrope } from "./ui/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Nav>
          <MenuModal />
        </Nav>

        {children}
      </body>
    </html>
  );
}
